#!/bin/bash
# script to create a tarball from the ESS driver CVS files
# jet 4/16/06
# presumes we are above the top directory of an ESS dir
# go find out what version we are
ver=`fgrep '#define DRIVER_VERSION' ess/essserial-2.6.c | cut -d ' ' -f 3`
# strip double quotes
ver=`eval echo $ver`
relname=ess_2.6-${ver}
tmpdirname=/tmp/${relname}_$$
cvs export -D today -d ${tmpdirname}/${relname} ess
# remove myself
rm ${tmpdirname}/${relname}/release
# add 111.zip
cp ess/111.zip  ${tmpdirname}/${relname}
# create a manifest with all the CVS versions
date > ${tmpdirname}/${relname}/manifest
cvs stat >> ${tmpdirname}/${relname}/manifest
# tar it up for release
tar -C ${tmpdirname} -cvzf ./${relname}.tar.gz ${relname}
# clean up directory
rm -rf ${tmpdirname}

