#!/bin/bash
# script to create a tarball from the ESS driver CVS files
# jet 4/16/06
# presumes we are above the top directory of an ESS dir
# go find out what version we are
ver=`fgrep '#define DRIVER_VERSION' ess/essserial-2.6.c | cut -d ' ' -f 3`
# strip double quotes
ver=`eval echo $ver`
relname=ess_2.6-${ver}
tmpdirname=/tmp/${relname}_$$
cvs -Q export -D today -d ${tmpdirname}/${relname} ess
# remove myself and binary-creating stuff
rm ${tmpdirname}/${relname}/release
rm ${tmpdirname}/${relname}/Makefile.mungebin
rm ${tmpdirname}/${relname}/fixup_relocs.c

# create a manifest with all the CVS versions
date > ${tmpdirname}/${relname}/manifest
cvs -q stat >> ${tmpdirname}/${relname}/manifest
# add the binary
cp ess/lib/esscom_bin.2.6.o ${tmpdirname}/${relname}/esscom_bin.2.6.o_shipped
# tar it up for release
tar -C ${tmpdirname} -czf ./${relname}.tar.gz ${relname}
# clean up directory
rm -rf ${tmpdirname}
echo created distribution tarball ${relname}.tar.gz in current directory

