#!/bin/bash
# script to create a tarball from the ESS driver git repo files
# jet 4/16/06
# presumes we are in the top directory of an ESS repo
# go find out what version we are
ver=`fgrep '#define DRIVER_VERSION' essserial-2.6.c | cut -d ' ' -f 3`
# strip double quotes
ver=`eval echo $ver`
relname=ess_2.6-${ver}
git archive --format=tar HEAD --output ./${relname}.tar
# remove this script, and binary-creating stuff
tar f ./${relname}.tar --delete release Makefile.mungebin fixup_relocs.c
# give tarball users the README that is for them, not the one that's for package builders
tar f ./${relname}.tar --delete README
tar f ./${relname}.tar --delete README.install
tar f ./${relname}.tar --transform s/README.install/README/ --append README.install

# create a manifest with all the file versions
date > manifest
git ls-tree HEAD >> manifest
# add the binary
tar rf ./${relname}.tar manifest esscom_bin.2.6.o_shipped
# clean up directory
rm manifest
gzip ./${relname}.tar
echo created distribution tarball ${relname}.tar.gz in current directory
